-- Add cities referenced in legacy data that don't exist yet
INSERT INTO public.cities (name, state, country) VALUES 
('CORBETT', 'Uttarakhand', 'India'),
('Ramnagar', 'Uttarakhand', 'India'),
('NAINITAL', 'Uttarakhand', 'India'),
('Haridwar', 'Uttarakhand', 'India'),
('Rishikesh', 'Uttarakhand', 'India'),
('Mussoorie', 'Uttarakhand', 'India'),
('Dehradun', 'Uttarakhand', 'India'),
('Lansdowne', 'Uttarakhand', 'India'),
('Dhanaulti', 'Uttarakhand', 'India'),
('Mukteshwar', 'Uttarakhand', 'India'),
('Bhimtal', 'Uttarakhand', 'India'),
('Kasol', 'Himachal Pradesh', 'India'),
('Dharamshala', 'Himachal Pradesh', 'India'),
('Dalhousie', 'Himachal Pradesh', 'India'),
('Chandigarh', 'Chandigarh', 'India'),
('Noida', 'Uttar Pradesh', 'India'),
('Ghaziabad', 'Uttar Pradesh', 'India'),
('Lucknow', 'Uttar Pradesh', 'India'),
('Mathura', 'Uttar Pradesh', 'India'),
('Vrindavan', 'Uttar Pradesh', 'India'),
('Ayodhya', 'Uttar Pradesh', 'India'),
('Allahabad', 'Uttar Pradesh', 'India'),
('Gurugram', 'Haryana', 'India'),
('Meerut', 'Uttar Pradesh', 'India'),
('Rohtak', 'Haryana', 'India'),
('Bilaspur', 'Chhattisgarh', 'India'),
('Ludhiana', 'Punjab', 'India'),
('Surat', 'Gujarat', 'India'),
('Jodhpur', 'Rajasthan', 'India'),
('Ranthambore', 'Rajasthan', 'India'),
('Pushkar', 'Rajasthan', 'India'),
('Sissu', 'Himachal Pradesh', 'India'),
('Srinagar', 'Jammu & Kashmir', 'India'),
('Andaman', 'Andaman & Nicobar', 'India')
ON CONFLICT DO NOTHING;