-- Import more agents batch 3 and another hotels and transporters
-- Agents batch 3 (101-150)
INSERT INTO public.agents (name, address, phone, email, commission_rate, notes, company_name) VALUES
('Kamad Holidays', 'Bhopal Madhya Pradesh', '9926651088', 'kamadtravel@gmail.com', 0, 'RINKESHKESHRVANI', 'Kamad Holidays'),
('Otilla', '', '', '', 0, 'Ravi', 'Otilla'),
('Star Vacations Pvt Ltd', '', '9634012238', 'manjeetsingh.mba@gmail.com', 0, 'Manjeet Singh 9634012238', 'Star Vacations Pvt Ltd'),
('Rose Tour & Travels', '73, 74, Mohan Singh Palace,Connaught Place New Delhi-01', '8826395556', 'Sales@rosetourtravels.com', 0, 'Manoj Kumar', 'Rose Tour & Travels'),
('Avakaza Travyou Pvt. Ltd.', '126 BASGAON, JEOLIKOTE, Nainital, Uttarakhand, India - 263127', '9758 806 806', '', 0, 'kamal katyal', 'Avakaza Travyou Pvt. Ltd.'),
('Uttrakhand Ventures', 'Delhi Office: GH-14/749, Main Road, Opp Nainital Bank, Paschim Vihar New Delhi 110087', '9999831144', 'ops@uttarakhandventures.com', 0, 'Dilmeet', 'Uttrakhand Ventures'),
('Cleartrip', '', '', '', 0, '', 'Cleartrip'),
('Qubix Holidays Sch Grp', 'mayur vihar, delhi', '9810790901', '', 0, 'Jagdish', 'Qubix Holidays Sch Grp'),
('Rewari Tours And Travels', 'rewari,hr', '', '', 0, 'rajneesh', 'Rewari Tours And Travels'),
('Uttrakhand Expert', '', '', '', 0, '', 'Uttrakhand Expert'),
('Destiny Travels', '', '', '', 0, '', 'Destiny Travels'),
('Siyaram Tour Travels', '', '98135 75655', 'Siyaramtourtravel@gmail.com', 0, 'Yogender Bhardwaj +91 98135 75655 / +917988245366', 'Siyaram Tour Travels'),
('Darien Resort', '', '', '', 0, '', 'Darien Resort'),
('Infinit Tour Holidays India', '', '8534082384', 'sales@infinitour.in', 0, 'Anshul Bansal', 'Infinit Tour Holidays India'),
('Bansal Tour & Travels', 'rohtak h.r', '9996656600', '', 0, 'Rahul Bansal', 'Bansal Tour & Travels'),
('Holiday Uncle', '', '', '', 0, 'Dhruv gaur', 'Holiday Uncle'),
('Delhi Tourism', '', '', '', 0, 'atul an panday tannu sharma', 'Delhi Tourism'),
('Agent Complimentary 1', '', '', '', 0, '', 'Agent Complimentary 1'),
('Cleartrip Agent', '', '', '', 0, 'sunil ji', 'Cleartrip'),
('Five Elements Centre', 'COMM 350 P.P', '+91 90138 73293', 'Info@fiveelementscentre.com', 0, 'YESH MUKUND', 'Five Elements Centre'),
('Grand Heritage', '', '', '', 0, 'meghna', 'Grand Heritage'),
('SUuryadoy Holidays Kolkota', '', '8918219160', '', 0, '', 'SUuryadoy Holidays'),
('FSR Travels Private Limited', '203-204, 2nd Floor, Emaar Palm Springs Plaza, The Palm Springs, Golf Corse Road, DLF Phase-5, Sector 54, Gurugram', '8130701957', 'Preeti.rajput@fsrtravels.com', 0, 'Preeti Rajput', 'FSR Travels Private Limited'),
('Ways India Travel', 'Pahargunj Delhi', '93123 64726', '', 0, 'Satvir 93123 64726', 'Ways India Travel'),
('Trago Travels', 'Pankaj bedi', '', '', 0, '', 'Trago Travels'),
('World Tour & Travel Services / WTT', 'B 2, Ground Floor, Neighborhood, Commercial complex, Next To SBI bank, Nerul [West], Navi Mumbai -400706', '810882 8516', 'meraj.worldtravels@gmail.com', 0, 'M Khan', 'World Tour & Travel Services'),
('Find My Trips', '', '', 'findmytripss@gmail.com', 0, '6378042644', 'Find My Trips'),
('Banaras Lanes', '', '8953869353', 'banaraslanes@gmail.com', 0, '', 'Banaras Lanes'),
('MJ Travels', '865, Sunlight Colony, 2nd Floor, Hari nagar, Ashram', '9654581005', 'mjtravels.solution@gmail.com', 0, 'Aman Massey 9654581005 / 9625862308', 'MJ Travels'),
('Vacation Maker', '', '', '', 0, 'Kapil yadav', 'Vacation Maker'),
('Kanav Getways India', '12/2 RAJ NAGAR MEERUT ROAD', '', '', 0, '', 'Kanav Getways India'),
('Traveller King', '', '', '', 0, 'Ritesh', 'Traveller King'),
('Mirza Tour & Travel', '', '', '', 0, '', 'Mirza Tour & Travel'),
('UMA TOURISM & HOLIDAYS PVT LTD', 'Khazana Complex, Sector K, Ashiyana, Lucknow, Uttar Pradesh 226012, India', '7880670926', 'ops3@umatourism.com', 0, 'KUMKUM', 'UMA TOURISM & HOLIDAYS PVT LTD'),
('Sukhadyatra.com', '202.Rudrakash tower, Laxminagar-110092', '85275 41674', 'info@sukhadyatra.com', 0, 'Akshat Kashyap - CEO', 'Sukhadyatra.com'),
('Universe Travels', '', '98970 07237', '', 0, 'Vishal Tyagi', 'Universe Travels'),
('Travsie', '', '', '', 0, '', 'Travsie'),
('Eon Hospitality', '', '', '', 0, '', 'Eon Hospitality'),
('Agoda', '', '', '', 0, '', 'Agoda'),
('OYO', '', '', '', 0, '', 'OYO'),
('Goibibo', '', '', '', 0, '', 'Goibibo'),
('Yatra.com', '', '', '', 0, '', 'Yatra.com'),
('EaseMyTrip', '', '', '', 0, '', 'EaseMyTrip'),
('Expedia', '', '', '', 0, '', 'Expedia'),
('Trip Advisor', '', '', '', 0, '', 'Trip Advisor'),
('Hotels.com', '', '', '', 0, '', 'Hotels.com'),
('Trivago', '', '', '', 0, '', 'Trivago'),
('HolidayIQ', '', '', '', 0, '', 'HolidayIQ'),
('Via.com', '', '', '', 0, '', 'Via.com'),
('Ixigo', '', '', '', 0, '', 'Ixigo');