// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zifegjopaxyelgboryua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppZmVnam9wYXh5ZWxnYm9yeXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNDEyMTYsImV4cCI6MjA3NTgxNzIxNn0.VC8xJEjzk0HMkUxWgfw5cLCBMw_A2_8Kh0OqfD0BtQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});